config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :products do
      resources :images do
        collection do
          get 'multi_upload'
        end
      end
    end
  end
end

app/models/image_decorator.rb
Spree::Image.class_eval do

  def to_jq_upload
    {
        'name' => read_attribute(:attachment_file_name),
        'size' => read_attribute(:attachment_file_size),
        'thumbnail_url' => attachment.url(:mini, false),
        'url' => attachment.url(:product, false),

        # TODO: find the way to generate edit and delete urls here
        #include Rails.application.routes.url_helpers doesn't work
        'edit_url' => '',
        'delete_url' => ''
    }
  end

end

app/controllers/spree/admin/images_controller_decorator.rb
Spree::Admin::ImagesController.class_eval do

  def create
    
    product = Spree::Product.where('slug' => params['product_id'])
    params[object_name][:attachment].each do |attachment_object|
      #@object.attributes = params[object_name]
      product = Spree::Product.where('slug' => params['product_id'])
      #@object = Spree::Image.create
      #@object.viewable.product = product
      #@object.viewable_id = product[0].id


      image = Spree::Image.new
      image.attachment = attachment_object
      image.viewable_id = params[:image][:viewable_id] #product[0].id
      image.type = 'Spree::Image'
      image.viewable_type = 'Spree::Variant'
      #binding.pry
      image.save

      #invoke_callbacks(:create, :before)
      #@object.attachment = attachment_object
      #@object.save
      #invoke_callbacks(:create, :after)
      
    end
    redirect_to '/admin/products/' + product[0].slug + '/images' #admin_product_url(product)
    
  end

  def multi_upload

  end

  def new_actions
    [:new, :create, :multi_upload]
  end
end

app/views/spree/admin/images/_template_download.html.erb
<script id="template-download" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
  <tr class="template-download fade">

    {% if (file.error) { %}

    <td class="name"><span>{%=file.name%}</span></td>
    <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
    <td class="error"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] ||
      file.error%}
    </td>

    {% } else { %}

    <td class="preview">{% if (file.thumbnail_url) { %}
      <a href="{%=file.url%}" title="{%=file.name%}" rel="gallery" download="{%=file.name%}"><img src="{%=file.thumbnail_url%}"></a>
      {% } %}
    </td>
    <td class="name">
      <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}</a>
    </td>
    <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>

    {% } %}

    <td class="actions">
      <a data-action="edit" class="icon_link with-tip icon-edit no-text" href="{%=file.edit_url%}" target="_blank"></a>
      <a url="{%=file.delete_url%}" data-confirm="<%= t(:are_you_sure) %>" data-action="remove" class="delete-resource icon_link with-tip icon-trash no-text" href="{%=file.delete_url%}"></a>
    </td>

  </tr>
  {% } %}
</script>

app/views/spree/admin/images/_template_upload.html.erb
<script id="template-upload" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
  <tr class="template-upload fade">
    <td class="preview"><span class="fade"></span></td>
    <td class="name"><span>{%=file.name%}</span></td>

    {% if (file.error) { %}
        <td class="error">
          <span class="label label-important"><%= t(:error) %></span>
          {%=locale.fileupload.errors[file.error] || file.error%}
        </td>
    {% } else if (o.files.valid) { %}
        <td class="size">
          <span>{%=o.formatFileSize(file.size)%}</span>
        </td>
    {% } %}

    <td class="actions">

      {% if (!o.options.autoUpload) { %}
      <span class="start">
        <button class="button icon-upload">{%=locale.fileupload.start%}</button>
      </span>
      {% } %}

      {% if (!i) { %}
      <span class="cancel">
        <button class="button icon-ban-circle">{%=locale.fileupload.cancel%}</button>
      </span>
      {% } %}

    </td>

  </tr>
  {% } %}
</script>

app/views/spree/admin/images/index.html.erb
<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => 'Images'} %>

<% content_for :page_actions do %>
  <% if can?(:create, Spree::Image) %>
    <li><%= link_to_with_icon('plus', "Multi Upload", multi_upload_admin_product_images_url(@product), :id => 'multi_upload_image_link', :class => 'button') %></li>
  <% end %>
<% end %>

<div id="images" data-hook></div>

<% unless @product.images.any? || @product.variant_images.any? %>
  <div class="no-objects-found">
    <%= Spree.t(:no_images_found) %>.
  </div>
<% else %>
  <table class="index sortable" data-hook="images_table" data-sortable-link="<%= update_positions_admin_product_images_url(@product) %>">
    <colgroup>
      <col style="width: 5%">
      <col style="width: 10%">
      <% if @product.has_variants? %>
        <col style="width: 25%">
      <% end %>
      <col style="width: 45%">
      <col style="width: 15%">
    </colgroup>
    <thead>
      <tr data-hook="images_header">
        <th colspan="2"><%= Spree.t(:thumbnail) %></th>
        <% if @product.has_variants? %>
          <th><%= Spree::Variant.model_name.human %></th>
        <% end %>
        <th><%= Spree::Image.human_attribute_name(:alt) %></th>
        <th class="actions"></th>
      </tr>
    </thead>

    <tbody>
      <% (@product.variant_images).each do |image| %>
        <tr id="<%= spree_dom_id image %>" data-hook="images_row" class="<%= cycle('odd', 'even')%>">
          <td class="no-border">
            <% if can?(:update_positions, Spree::Image) %>
              <span class="handle"></span>
            <% end %>
          </td>
          <td>
            <%= link_to image_tag(image.attachment.url(:mini)), image.attachment.url(:product) %>
          </td>
          <% if @product.has_variants? %>
            <td><%= options_text_for(image) %></td>
          <% end %>
          <td><%= image.alt %></td>
          <td class="actions">
            <% if can?(:update, image) %>
              <%= link_to_with_icon 'edit', Spree.t('actions.edit'), edit_admin_product_image_url(@product, image), :no_text => true, :data => {:action => 'edit'} %>
            <% end %>
            <% if can?(:destroy, image) %>
              <%= link_to_delete image, { :url => admin_product_image_url(@product, image), :no_text => true } %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/spree/admin/images/multi_upload.html.erb
<%= render :partial => 'spree/admin/shared/product_tabs', :locals => { :current => 'Images' } %>

<%= render :partial => 'spree/shared/error_messages', :locals => {:target => @product} %>

<%= form_for [:admin, @product, @image], :html => {:multipart => true, :id => "fileupload", :method => :post} do |f| %>
    <fieldset data-hook="new_product">
      <legend align="center"><%= t('multi_upload.title') %></legend>

      <div class="row fileupload-buttonbar">
        <div data-hook="variant" class="field">
          <%= f.label Spree::Variant.model_name.human %>
          <br>
          <%= f.select :viewable_id, @variants, {}, {:class => 'select2'} %>
        </div>

        <span class="icon-plus button fileinput-button">
            <%= t('multi_upload.add_files') %>
            <%= f.file_field :attachment, {:multiple => true} %>
        </span>

        <button type="submit" class="icon-upload button start"><%= t('multi_upload.start') %></button>
        <button type="reset" class="icon-ban-circle button cancel"><%= t('multi_upload.cancel') %></button>

      </div>

      <div class="fileupload-progress fade">
        <div class="progress-extended">&nbsp;</div>
      </div>

      <br />

      <table role="presentation" class="table table-striped">
        <tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody>
      </table>

    </fieldset>
<% end %>

<script type="text/javascript" charset="utf-8">
    $(function () {
        $('#fileupload').fileupload();
    });
</script>

<%= render :partial => 'template_upload' %>
<%= render :partial => 'template_download' %>

app/views/spree/admin/images/multi_upload.js.erb
$("#images").html('<%= escape_javascript(render :template => "spree/admin/images/multi_upload", :formats => [:html], :handlers => [:erb]) %>');

// TODO: configure plugin: e. g. set appropriate preview sizes
$('#multi_upload').fileupload();